// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HousePricePrediction
{
    public class ModelOutput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }

        [ColumnName("Score")]
        public float SalePrice { get; set; }

        public override string ToString() => $"{Id},{SalePrice}";
    }
}
